import type { Config } from 'tailwindcss';

export default {
	darkMode: ['class'],
	content: ['./index.html', './src/**/*.{ts,tsx}'],
	theme: {
		extend: {
			fontFamily: {
				sans: ['Geist', 'system-ui', '-apple-system', 'sans-serif'],
				mono: ['Geist Mono', 'ui-monospace', 'SFMono-Regular', 'monospace'],
			},
			colors: {
				border: 'hsl(var(--border))',
				input: 'hsl(var(--input))',
				ring: 'hsl(var(--ring))',
				background: 'hsl(var(--background))',
				foreground: 'hsl(var(--foreground))',
				primary: {
					DEFAULT: 'hsl(var(--primary))',
					foreground: 'hsl(var(--primary-foreground))',
				},
				secondary: {
					DEFAULT: 'hsl(var(--secondary))',
					foreground: 'hsl(var(--secondary-foreground))',
				},
				destructive: {
					DEFAULT: 'hsl(var(--destructive))',
					foreground: 'hsl(var(--destructive-foreground))',
				},
				muted: {
					DEFAULT: 'hsl(var(--muted))',
					foreground: 'hsl(var(--muted-foreground))',
				},
				accent: {
					DEFAULT: 'hsl(var(--accent))',
					foreground: 'hsl(var(--accent-foreground))',
				},
				popover: {
					DEFAULT: 'hsl(var(--popover))',
					foreground: 'hsl(var(--popover-foreground))',
				},
				card: {
					DEFAULT: 'hsl(var(--card))',
					foreground: 'hsl(var(--card-foreground))',
				},
				// shadcn Sidebar palette (theme-aware via CSS variables).
				sidebar: {
					DEFAULT: 'hsl(var(--sidebar))',
					foreground: 'hsl(var(--sidebar-foreground))',
					primary: 'hsl(var(--sidebar-primary))',
					'primary-foreground': 'hsl(var(--sidebar-primary-foreground))',
					accent: 'hsl(var(--sidebar-accent))',
					'accent-foreground': 'hsl(var(--sidebar-accent-foreground))',
					border: 'hsl(var(--sidebar-border))',
					ring: 'hsl(var(--sidebar-ring))',
				},
				// Meshify semantic palette — theme-aware via CSS variables. Dark-first;
				// `.light` overrides in index.css. Actions/Mesh identity are indigo→iris;
				// neutrals run ink → muted. `-lo` shades are on-tint text colors.
				mc: {
					bg: 'hsl(var(--mc-bg) / <alpha-value>)',
					card: 'hsl(var(--mc-card) / <alpha-value>)',
					surface: 'hsl(var(--mc-surface) / <alpha-value>)',
					raised: 'hsl(var(--mc-raised) / <alpha-value>)',
					accent: 'hsl(var(--mc-accent) / <alpha-value>)',
					'accent-hi': 'hsl(var(--mc-accent-hi) / <alpha-value>)',
					'accent-lo': 'hsl(var(--mc-accent-lo) / <alpha-value>)',
					success: 'hsl(var(--mc-success) / <alpha-value>)',
					'success-lo': 'hsl(var(--mc-success-lo) / <alpha-value>)',
					indexing: 'hsl(var(--mc-indexing) / <alpha-value>)',
					danger: 'hsl(var(--mc-danger) / <alpha-value>)',
					'danger-lo': 'hsl(var(--mc-danger-lo) / <alpha-value>)',
					purple: 'hsl(var(--mc-purple) / <alpha-value>)',
					'purple-lo': 'hsl(var(--mc-purple-lo) / <alpha-value>)',
					teal: 'hsl(var(--mc-teal) / <alpha-value>)',
					amber: 'hsl(var(--mc-amber) / <alpha-value>)',
					'amber-lo': 'hsl(var(--mc-amber-lo) / <alpha-value>)',
					text: 'hsl(var(--mc-text) / <alpha-value>)',
					'text-2': 'hsl(var(--mc-text-2) / <alpha-value>)',
					'text-3': 'hsl(var(--mc-text-3) / <alpha-value>)',
					muted: 'hsl(var(--mc-muted) / <alpha-value>)',
					'muted-2': 'hsl(var(--mc-muted-2) / <alpha-value>)',
					// Hairline borders carry their own alpha.
					border: 'var(--mc-border)',
					hairline: 'var(--mc-hairline)',
				},
			},
			borderRadius: {
				sm: 'calc(var(--radius) - 4px)',
				md: 'calc(var(--radius) - 2px)',
				lg: 'var(--radius)',
				xl: 'calc(var(--radius) + 4px)',
				'2xl': 'calc(var(--radius) + 10px)',
				'3xl': 'calc(var(--radius) + 18px)',
			},
			// Elevation — theme-aware via CSS variables (see index.css).
			boxShadow: {
				e1: 'var(--e1)',
				e2: 'var(--e2)',
				e3: 'var(--e3)',
				e4: 'var(--e4)',
				'glow-accent': 'var(--glow-accent)',
				'glow-accent-lg': 'var(--glow-accent-lg)',
				'glow-purple': 'var(--glow-purple)',
				'glow-purple-lg': 'var(--glow-purple-lg)',
			},
			// Type scale — a calm, tight-tracked SaaS ramp (Linear/Vercel feel).
			fontSize: {
				micro: ['10px', { lineHeight: '14px', letterSpacing: '.02em' }],
				label: ['11px', { lineHeight: '15px', letterSpacing: '.08em' }],
				caption: ['12px', { lineHeight: '17px' }],
				sm2: ['13px', { lineHeight: '19px' }],
				body: ['14px', { lineHeight: '22px' }],
				lead: ['15px', { lineHeight: '24px' }],
				h3: ['18px', { lineHeight: '26px', letterSpacing: '-.01em' }],
				h2: ['22px', { lineHeight: '29px', letterSpacing: '-.02em' }],
				h1: ['30px', { lineHeight: '36px', letterSpacing: '-.028em' }],
				display: ['46px', { lineHeight: '1.04', letterSpacing: '-.035em' }],
				'display-lg': ['74px', { lineHeight: '1.0', letterSpacing: '-.04em' }],
			},
			transitionTimingFunction: {
				'out-expo': 'cubic-bezier(.22,1,.36,1)',
			},
			keyframes: {
				meshpulse: { '0%,100%': { opacity: '1' }, '50%': { opacity: '.35' } },
				breathe: { '0%,100%': { opacity: '.55', transform: 'scale(1)' }, '50%': { opacity: '.9', transform: 'scale(1.04)' } },
				beam: { '0%': { transform: 'translateX(-120%)' }, '100%': { transform: 'translateX(320%)' } },
				twinkle: { '0%,100%': { opacity: '.2' }, '50%': { opacity: '.9' } },
				float: { '0%,100%': { transform: 'translateY(0)' }, '50%': { transform: 'translateY(-6px)' } },
				rise: { '0%': { opacity: '0', transform: 'translateY(46px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
				textin: { '0%': { opacity: '0', filter: 'blur(14px)', transform: 'translateY(16px)' }, '100%': { opacity: '1', filter: 'blur(0)', transform: 'translateY(0)' } },
				drift: { '0%,100%': { transform: 'translate(0,0)' }, '50%': { transform: 'translate(10px,-22px)' } },
				lamp: { '0%,100%': { opacity: '.45' }, '50%': { opacity: '.8' } },
				dash: { to: { strokeDashoffset: '-240' } },
				fade: { '0%': { opacity: '0', transform: 'translateY(4px)' }, '100%': { opacity: '1', transform: 'translateY(0)' } },
				shimmer: { '100%': { transform: 'translateX(100%)' } },
			},
			animation: {
				meshpulse: 'meshpulse 1.6s infinite',
				breathe: 'breathe 2.4s infinite',
				beam: 'beam 3.4s infinite linear',
				twinkle: 'twinkle 3s infinite',
				float: 'float 5s infinite ease-in-out',
				rise: 'rise 1.1s cubic-bezier(.22,1,.36,1) both',
				textin: 'textin .9s ease-out both',
				drift: 'drift 10s ease-in-out infinite',
				lamp: 'lamp 6s ease-in-out infinite',
				dash: 'dash 9s linear infinite',
				fade: 'fade .22s ease-out both',
				shimmer: 'shimmer 1.6s infinite',
			},
		},
	},
	plugins: [require('tailwindcss-animate')],
} satisfies Config;
